ui_print "INSTALLING"
ui_print ""
ui_print "Unlock game graphic and fps such as Call of Duty Mobile and PUBG etc"
ui_print ""
ui_print "3"
ui_print "2"
ui_print "1"
ui_print ""
ui_print "FPS Unlocker BY REDFOX"
ui_print ""
ui_print ""
ui_print "---------------------------------"
ui_print "Successfully changed device model"
ui_print "          Happy gaming!          "
ui_print "---------------------------------"
